### ISSUE TITLE
License key not found

### ISSUE THREAD

**Issue by bs16b013** [Jatin-Pawar/ManoMotion_GrabAndMove#2]
Hi,
I followed the steps you provided. I build and ran successfully but i am getting "License Key not found" in my mobile while running the application. I made sure to give my manomotion license key and packagename. Could you help me to resolve this.

**Comment by Jatin-Pawar** [comment]
Hey @bs16b013,
I worked on this a long time ago when Manomotion in beta testing, so a few probable reasons could be:
1) Manomotion SDK is old and now they have updated the way they check for the License Key.
2) Another reason this issue could be caused is maybe because of your internet connectivity. As far as, I know Manomotion checks the license key over internet. So make sure you have proper connectivity while running the app.

Try these possible solutions and let me know.
